### ISSUE TITLE
Fails to start httpd

### ISSUE THREAD

**Issue by IanVaughan** [cywolf/schemaspy-docker#2]
After generating all the schema etc, `start.sh` errors on staring the httpd server
```
...
INFO  - Started Main in 55.556 seconds (JVM running for 56.112)
Starting webserver on port 8080
start.sh: line 74: httpd: not found
```

**Comment by IanVaughan** [comment]
I have a fix that solves it via using PHP instead https://github.com/quiqupltd/schemaspy-docker/pull/1

I'll tidy that up and submit an MR here in a bit.

**Comment by andrewwhitehead** [comment]
Fixed by adding the busybox-extras package.
